/**
 * Render docs/connect-an-agent.md from lib/mcp/connect-clients.ts.
 *
 * The connection how-to exists in three places — the in-app guide, the public
 * docs page, and this markdown file — and there is exactly one copy of the
 * content behind all of them. Hand-editing the markdown is therefore a mistake
 * that would be silently reverted, so the file says so at the top and
 * `--check` fails a build that has let the two drift.
 *
 *   npx tsx scripts/generate-connect-doc.ts          # write
 *   npx tsx scripts/generate-connect-doc.ts --check  # verify, exit 1 on drift
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  buildConnectClients,
  buildServerUrlForms,
  CLAUDE_EGRESS_RANGE,
  CONNECT_TROUBLESHOOTING,
  type ConnectMethod,
  type ConnectStepGroup,
  KNOWN_CALLBACK_URLS,
  METHOD_NAMES,
  PREREQUISITE,
  REACHABILITY,
  SELF_HOST_REQUIREMENTS,
  SERVER_URL_PLACEHOLDER,
  THIS_APP,
} from "../lib/mcp/connect-clients";

// Run from the repository root; tsx compiles this to CJS on Node 20, where
// import.meta.dirname is undefined.
const OUT = join(process.cwd(), "docs", "connect-an-agent.md");
if (!existsSync(join(process.cwd(), "docs"))) {
  console.error("Run this from the repository root.");
  process.exit(1);
}
const SERVER_URL = SERVER_URL_PLACEHOLDER;

function table(head: string[], rows: string[][]): string {
  const sep = head.map(() => "---");
  return [head, sep, ...rows].map((row) => `| ${row.join(" | ")} |`).join("\n");
}

function method(
  entry: ConnectMethod,
  methodName: string,
  prerequisite: string,
): string {
  const out: string[] = [];
  // The protocol name is the heading: a reader scanning for "OAuth 2.1" or
  // "Bearer auth" should not have to infer it from "Add it to mcp.json".
  out.push(`### ${methodName}`, "", `**${entry.heading}**`, "");

  // Anything to paste comes before the steps that say to paste it. After
  // them it is a reference for work already done.
  if (entry.snippet) {
    if (entry.snippet.location) {
      out.push(`\`${entry.snippet.location}\``, "");
    }
    const fence = "```";
    out.push(
      `${fence}${entry.snippet.language}`,
      entry.snippet.code,
      fence,
      "",
    );
  }

  // The app is created here, configured in the client, and approved back
  // here. One heading per hop, and the numbering runs straight through so a
  // reader never loses their place across the boundary.
  const groups: ConnectStepGroup[] = [
    { app: THIS_APP, steps: [prerequisite] },
    ...entry.groups,
  ];
  let n = 0;
  for (const group of groups) {
    out.push(`*In ${group.app}*`, "");
    for (const step of group.steps) {
      n += 1;
      out.push(`${n}. ${step}`);
    }
    out.push("");
  }

  if (entry.note) {
    out.push(`⚠️ ${entry.note}`, "");
  }
  return out.join("\n");
}

function render(): string {
  const clients = buildConnectClients(SERVER_URL);
  const out: string[] = [];

  out.push(
    "<!-- Generated by scripts/generate-connect-doc.ts from",
    "     lib/mcp/connect-clients.ts. Do not edit by hand: the in-app guide and",
    "     the public docs page render from that same file, and editing only this",
    "     copy is how the three fall out of step. -->",
    "",
    "# Connect an agent",
    "",
    "Point Claude, Cursor, Gemini, ChatGPT or anything else that speaks MCP",
    "at your NetSuite workspace.",
    "",
    "",
    "---",
    "",
    "## Server URL",
    "",
    "Every client below takes the same URL. **App Portal \u2192 Agent apps**",
    "shows yours, with a copy button.",
    "",
    table(
      ["Install", "Server URL"],
      buildServerUrlForms().map((form) => [form.label, `\`${form.url}\``]),
    ),
    "",
    "---",
    "",
  );

  for (const client of clients) {
    out.push(`## ${client.docHeading}`, "");
    if (client.signIn) {
      out.push(method(client.signIn, METHOD_NAMES.signIn, PREREQUISITE.signIn));
    }
    if (client.agentKey) {
      out.push(
        method(client.agentKey, METHOD_NAMES.agentKey, PREREQUISITE.agentKey),
      );
    }
  }

  out.push(
    "---",
    "",
    "## If the connector asks for a client ID and secret",
    "",
    "Tick **This connector asks for a client ID and secret** when you create the",
    "app, and give it the connector's callback URL:",
    "",
    table(
      ["Connector", "Callback URL"],
      KNOWN_CALLBACK_URLS.map((row) => [
        row.label,
        row.url ? `\`${row.url}\`` : (row.note ?? ""),
      ]),
    ),
    "",
    "---",
    "",
    "## Can the AI reach your install?",
    "",
    table(
      ["Client", "Runs on", "Reaches a LAN-only install"],
      REACHABILITY.map((row) => [row.clients, row.runsOn, row.lanOnly]),
    ),
    "",
    `Claude's egress range is \`${CLAUDE_EGRESS_RANGE}\` if you would rather`,
    "allowlist than publish.",
    "",
    "---",
    "",
    "## Self-hosting",
    "",
    "Every install is its own authorization server. Two things have to be true,",
    "and **App Portal → Agent apps** warns you when they are not:",
    "",
    ...SELF_HOST_REQUIREMENTS.map((line, index) => `${index + 1}. ${line}`),
    "",
    "---",
    "",
    "## Troubleshooting",
    "",
    table(
      ["Symptom", "Cause", "Fix"],
      CONNECT_TROUBLESHOOTING.map((row) => [row.symptom, row.cause, row.fix]),
    ),
    "",
    "---",
    "",
    "## Managing agent apps",
    "",
    "**App Portal → Agent apps** lists every app, whichever way it connects.",
    "Open one to rename it, change its persona, copy or replace its credential,",
    "or revoke it.",
    "",
    "What each credential is, what an app reaches and what the endpoint returns",
    "are in [MCP server](mcp-server.md).",
    "",
    "",
  );

  return `${out
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()}\n`;
}

const rendered = render();

if (process.argv.includes("--check")) {
  const current = readFileSync(OUT, "utf8");
  if (current !== rendered) {
    console.error(
      "docs/connect-an-agent.md is out of date.\n" +
        "Run: npx tsx scripts/generate-connect-doc.ts",
    );
    process.exit(1);
  }
  console.log("docs/connect-an-agent.md is up to date.");
} else {
  writeFileSync(OUT, rendered);
  console.log(`Wrote ${OUT}`);
}
