/**
 * Render docs/connect-an-agent.md from lib/mcp/connect-clients.ts.
 *
 * The connection how-to exists in three places — the in-app guide, the public
 * docs page, and this markdown file — and there is exactly one copy of the
 * content behind all of them. Hand-editing the markdown is therefore a mistake
 * that would be silently reverted, so the file says so at the top and
 * `--check` fails a build that has let the two drift.
 *
 *   npx tsx scripts/generate-connect-doc.ts          # write
 *   npx tsx scripts/generate-connect-doc.ts --check  # verify, exit 1 on drift
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  AGENT_FIELDS,
  buildConnectClients,
  CLAUDE_EGRESS_RANGE,
  CONNECT_TROUBLESHOOTING,
  type ConnectMethod,
  KEY_PLACEHOLDER,
  METHOD_COMPARISON,
  METHOD_GUIDANCE,
  PREREQUISITE,
  REACHABILITY,
  SELF_HOST_REQUIREMENTS,
  SERVER_URL_PLACEHOLDER,
} from "../lib/mcp/connect-clients";

// Run from the repository root; tsx compiles this to CJS on Node 20, where
// import.meta.dirname is undefined.
const OUT = join(process.cwd(), "docs", "connect-an-agent.md");
if (!existsSync(join(process.cwd(), "docs"))) {
  console.error("Run this from the repository root.");
  process.exit(1);
}
const SERVER_URL = SERVER_URL_PLACEHOLDER;

function table(head: string[], rows: string[][]): string {
  const sep = head.map(() => "---");
  return [head, sep, ...rows].map((row) => `| ${row.join(" | ")} |`).join("\n");
}

function method(entry: ConnectMethod, prerequisite: string): string {
  const out: string[] = [];
  out.push(`**${entry.heading}**`, "");
  const steps = [prerequisite, ...entry.steps];
  out.push(...steps.map((step, index) => `${index + 1}. ${step}`), "");
  if (entry.snippet) {
    if (entry.snippet.location) {
      out.push(`\`${entry.snippet.location}\``, "");
    }
    const fence = "```";
    out.push(
      `${fence}${entry.snippet.language}`,
      entry.snippet.code,
      fence,
      "",
    );
  }
  if (entry.note) {
    out.push(`⚠️ ${entry.note}`, "");
  }
  return out.join("\n");
}

function render(): string {
  const clients = buildConnectClients(SERVER_URL);
  const out: string[] = [];

  out.push(
    "<!-- Generated by scripts/generate-connect-doc.ts from",
    "     lib/mcp/connect-clients.ts. Do not edit by hand: the in-app guide and",
    "     the public docs page render from that same file, and editing only this",
    "     copy is how the three fall out of step. -->",
    "",
    "# Connect an agent",
    "",
    "Point Claude, Cursor, VS Code, Gemini CLI, ChatGPT or anything else that",
    "speaks MCP at your NetSuite workspace.",
    "",
    "Two steps: **create the agent in the app**, then **point the AI at it**.",
    "",
    "---",
    "",
    "## 1. Create the agent",
    "",
    "Open **App Portal → Agent access**, copy the **Server URL**, then click",
    "**New agent**:",
    "",
    table(
      ["Field", "What it does"],
      AGENT_FIELDS.map((row) => [row.field, row.does]),
    ),
    "",
    "The two connection methods:",
    "",
    table(
      ["", "**Sign-in**", "**Agent key**"],
      METHOD_COMPARISON.map((row) => [row.label, row.signIn, row.agentKey]),
    ),
    "",
    METHOD_GUIDANCE.signIn,
    "",
    METHOD_GUIDANCE.agentKey,
    "",
    "---",
    "",
    "## 2. Point the AI at it",
    "",
    `Replace \`${SERVER_URL}\` with your Server URL, and \`${KEY_PLACEHOLDER}\` with your key.`,
    "",
  );

  for (const client of clients) {
    out.push(`### ${client.docHeading}`, "");
    if (client.signIn) {
      out.push(method(client.signIn, PREREQUISITE.signIn));
    }
    out.push(method(client.agentKey, PREREQUISITE.agentKey));
  }

  out.push(
    "---",
    "",
    "## Can the AI reach your install?",
    "",
    table(
      ["Client", "Runs on", "Reaches a LAN-only install"],
      REACHABILITY.map((row) => [row.clients, row.runsOn, row.lanOnly]),
    ),
    "",
    `Claude's egress range is \`${CLAUDE_EGRESS_RANGE}\` if you would rather`,
    "allowlist than publish.",
    "",
    "---",
    "",
    "## Self-hosting",
    "",
    "Sign-in works on every install with no extra configuration — each one is",
    "its own authorization server. Two things have to be true, and **App Portal",
    "→ Agent access** warns you when they are not:",
    "",
    ...SELF_HOST_REQUIREMENTS.map((line, index) => `${index + 1}. ${line}`),
    "",
    "---",
    "",
    "## Troubleshooting",
    "",
    table(
      ["Symptom", "Cause", "Fix"],
      CONNECT_TROUBLESHOOTING.map((row) => [row.symptom, row.cause, row.fix]),
    ),
    "",
    "---",
    "",
    "## Managing agents",
    "",
    "**App Portal → Agent access → Agents** lists every agent, whichever way it",
    "connects. Rename, change persona, replace a key, or revoke. Revoking is",
    "immediate: the next call gets `401`.",
    "",
    "Self-hosting details and the protocol reference are in",
    "[MCP server](mcp-server.md).",
    "",
  );

  return `${out
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()}\n`;
}

const rendered = render();

if (process.argv.includes("--check")) {
  const current = readFileSync(OUT, "utf8");
  if (current !== rendered) {
    console.error(
      "docs/connect-an-agent.md is out of date.\n" +
        "Run: npx tsx scripts/generate-connect-doc.ts",
    );
    process.exit(1);
  }
  console.log("docs/connect-an-agent.md is up to date.");
} else {
  writeFileSync(OUT, rendered);
  console.log(`Wrote ${OUT}`);
}
